language: node_js
node_js:
    - "8"
cache:
    directories:
        - "node_modules"
sudo: enabled
os: linux
script:
- ./build.sh

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: out
    on:
        branch: 
