language: node_js
node_js:
    - "8"
sudo: required
dist: trusty
os: linux
script:
- ./build.sh
before_install:
- sudo apt-get update
- sudo apt-get install -y miredo
#deploy:
    #provider: pages
    #skip_cleanup: true
    #github-token: $GITHUB_TOKEN
    #local-dir: out
