#!/usr/bin/env node
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

var Peers = require("./peers/index.js");
var fs = require('fs');

const getPeers = function () {
    return Peers.map(function (creds, path) {
        if (typeof creds.location !== 'undefined')
            delete creds.location;

        for (const peer in creds)
            if (creds.hasOwnProperty(peer))
                if (peer.indexOf('[') === -1)
                    return {
                        [peer]: creds[peer]
                    };
    });
}

const arrayToObject = function (array) {
    return array.reduce(function (result, item) {
        var key = Object.keys(item)[0];
        result[key] = item[key];
        return result;
    }, {});
}

peers = arrayToObject(getPeers());

var CONFIG = require("./cjdroute.conf");
CONFIG.interfaces.UDPInterface[0].connectTo = peers;

console.log(JSON.stringify(CONFIG));
